language: rust
rust:
  - stable
cache: cargo
script:
  - cargo build --release --all
os:
  - linux
  - windows
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - export TRAVIS_TAG="latest"-$TRAVIS_OS_NAME
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  overwrite: true
  name: $TRAVIS_OS_NAME
  api_key:
    secure: PQJQojy5jxfNO7Bx0MQ8a7M3HVjJlH2E0jvFc1VpR3M6XgphdIOqRkDPRC6t9Ie2mucNs4a7SlUNMxMLs9ZAch17o/naN6oCK1zgSE/dbQ8V7SiAB7zF5rfIA0Yv0xcjTfrLYLnMSBRA7oHH57oW5V5N3ZbRose4+xQAimMzmVYTgtkEG37N2/Z4PoUa0Z0+0A8AXA019zLCuxFDzDVMD+NKpHykgm48mAnuadnDotK2olBBehWyIPTnli6m2pNMKsxHZMXzqtSBUHIzVJaj4sZJSzN3hHLs7OJObkwNKZA1CNIyx1HvD4oH2EfW2znMcGG1KRHPsgOSrY+yQ3t/woaL8LEJCviI1RZM9z084bpGgcqFXM67xz9jJiTMijVkTyBPp5rLD9ry5C4+5E9+vCoLXoCAC7M08mGIuAxP9+s+GAD19/80KvX2dEFe7HhKDOnMCGrLX8U7RmfCH3FDLG9EYd4kQXhRLGQFBvpXxmVTxkfhSfU2EI9Hy2L4OnX7oYiKO8tgi86Cw++VmgCS3B8sgEbDH7BRah0vFxz32DtjPOEOWVlxdkBImEbXKoXB4L5+Xy2Qt9aXVnkkZURcHcu2qIB/IBQDeuqWPmMH0y3589l8D7UNS1DJ3GGyzhqmko6ldKd1gssxvPtTbp520UpaDkpXTdqv4ldmQ8DGYs8=
  file:
    - ./target/release/orbtk-thermostat
    - ./target/release/orbtk-thermostat.exe
  on:
    tags: true
    repo: Psykopear/test-rust-build
